# Generated by Django 3.2.9 on 2021-11-26 08:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='filmcast',
            options={'verbose_name': 'Cast'},
        ),
        migrations.AlterField(
            model_name='film',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='films', to='films.category'),
        ),
    ]
