# Generated by Django 3.2.9 on 2021-11-28 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0002_auto_20211126_0232'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='film',
            constraint=models.CheckConstraint(check=models.Q(('price__gte', 1.0)), name='price__gte_one'),
        ),
    ]
