# Generated by Django 3.2.9 on 2021-12-03 01:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('casts', '0003_rename_cast_castmember'),
        ('films', '0003_film_price__gte_one'),
    ]

    operations = [
        migrations.RenameField(
            model_name='filmcast',
            old_name='cast',
            new_name='member',
        ),
        migrations.AlterUniqueTogether(
            name='filmcast',
            unique_together={('movie', 'member', 'role')},
        ),
    ]
