# Generated by Django 3.2.9 on 2021-12-03 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('casts', '0003_rename_cast_castmember'),
        ('films', '0004_auto_20211202_1911'),
    ]

    operations = [
        migrations.RenameField(
            model_name='filmcast',
            old_name='movie',
            new_name='film',
        ),
        migrations.AlterUniqueTogether(
            name='filmcast',
            unique_together={('film', 'member', 'role')},
        ),
    ]
