# Generated by Django 3.2.9 on 2021-11-26 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('casts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cast',
            options={'verbose_name': 'Cast member', 'verbose_name_plural': 'Cast members'},
        ),
    ]
