# Generated by Django 3.2.9 on 2021-12-03 01:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0003_film_price__gte_one'),
        ('casts', '0002_alter_cast_options'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cast',
            new_name='CastMember',
        ),
    ]
