# Generated by Django 3.2.9 on 2021-12-02 05:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rent',
            name='days_rented',
        ),
        migrations.AddField(
            model_name='rent',
            name='rented_days',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MaxValueValidator(15), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='rent',
            name='extra_day_fee',
            field=models.DecimalField(decimal_places=2, default=2.0, max_digits=5, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='rent',
            name='returned_at',
            field=models.DateField(null=True),
        ),
    ]
