# Generated by Django 3.2.9 on 2021-12-06 13:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_alter_rent_extra_day_fee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rent',
            name='extra_day_fee',
            field=models.DecimalField(decimal_places=2, default=2.0, max_digits=5, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
